version: '3.8'

services:
  web:
    build: .
    container_name: python_sms_agent
    ports:
      - "5001:5000" # Expose container port 5000 to host port 5001
    env_file:
      - .env # Load environment variables from .env file
    # This command is updated to ensure Flask listens on all network interfaces,
    # making it accessible to the ngrok container.
    command: flask run --host=0.0.0.0

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_for_sms_agent
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN} # Get your ngrok authtoken from your ngrok dashboard
    command: http python_sms_agent:5000 # Forward to our web service container on port 5000
    depends_on:
      - web